name: GitHub Pages

on:
  push:
    branches:
      - master
      - develop
    pull_request:
     types: [opened, synchronize]

env:
  cache-version: v2

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest-bash]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # - name: Cache dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-${{ env.cache-name }}-

      # - run: |
      #    if [ "$RUNNER_OS" == "Linux" -o "$RUNNER_OS" == "macOS" ]; then
      #         rm -rf node_modules
      #    elif [ "$RUNNER_OS" == "Windows" ]; then
      #         rd /s /q node_modules
      #    else
      #         echo "$RUNNER_OS not supported"
      #         exit 1
      #    fi

      - run: rm -rf node_modules

      - run: npm install 
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
